Develop
Grek-88/goit-markup-hw-03 pull request #2
Opened 2020-12-30 19:41 UTC by Grek-88

2021-01-01 17:56 UTC, magom001 requested changes
Нет ссылки на страницу

2021-01-01 17:56 UTC, magom001 commented on css/style.css
>    color: #000000;
цвет не в переменной

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  /* padding-top: 200px; */
мертвый код

2021-01-01 17:56 UTC, magom001 commented on css/style.css
>    background: #2f303a;
цвет не в переменной

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  width: calc((100% - 90px) / 4);
в будущем никто не вспомнит и не поймет, что это за магическая формула. В эти случаях числа нужно уносить в переменные с говорящими названиями, или делать комментарий и объяснять, что тут за магия.

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  background: #f5f4fa;
цвет не в переменной

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 1px rgba(0, 0, 0, 0.14),
Что тут творится? Я уверен, что в фигме не так.

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  background: #2f303a;
цвет не в переменной

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  background: #f5f4fa;
цвет не в переменной

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  border: 1px solid #eeeeee;
цвет не в переменной

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +/* .footer .container {
мертвый код

2021-01-01 17:56 UTC, magom001 commented on css/style.css
> +  /* border: 2px solid green; */
мертвый код

2021-01-09 09:48 UTC, Grek-88 commented on css/style.css
>    color: #000000;
добавил в readme

2021-01-09 09:49 UTC, Grek-88 commented
> Нет ссылки на страницу

добавил в readme

2021-01-09 09:53 UTC, Grek-88 commented on css/style.css
>    color: #000000;
убрал в переменную, хотя он использовался в единичном месте, поэтому и не делал этого сразу.

2021-01-09 09:54 UTC, Grek-88 commented on css/style.css
> +  /* padding-top: 200px; */
убрал

2021-01-09 09:57 UTC, Grek-88 commented on css/style.css
>    background: #2f303a;
убрал в переменную

2021-01-09 09:58 UTC, Grek-88 commented on css/style.css
> +  background: #2f303a;
убрал в переменную

2021-01-09 10:08 UTC, Grek-88 commented on css/style.css
> +  width: calc((100% - 90px) / 4);
добавил комментарии в css, высчитываем ширину элементов так, чтобы поместилось по 4шт в ряд +маржин 30px, для будущего расширения контента(и/или для будущей адаптации под другие устройства).
не хочу плодить переменные из-за одной сточки, т.к. на странице портфолио такая же история, но уже по 3шт в ряду, а это опять новая переменная и т.д.
просто добавил комментарии.
Репета сказал можно ставить вообще просто фикс ширину и это не будет ошибкой, но такое вычисление более адаптивно.

2021-01-09 10:14 UTC, Grek-88 commented on css/style.css
> +  background: #f5f4fa;
убрал в переменную

2021-01-09 10:17 UTC, Grek-88 commented on css/style.css
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 1px rgba(0, 0, 0, 0.14),
Сам в шоке)))
но скопировал из сигмы
![image](https://user-images.githubusercontent.com/73738671/104089088-f123a700-527c-11eb-9838-f18b9270d0b4.png)

2021-01-09 10:17 UTC, Grek-88 commented on css/style.css
> +  background: #f5f4fa;
убрал в переменную

2021-01-09 10:20 UTC, Grek-88 commented on css/style.css
> +  border: 1px solid #eeeeee;
цвет рамки, еще и такой редкий, лишние строки эти писать, стоит оно того?точно ли надо?

2021-01-09 10:21 UTC, Grek-88 commented on css/style.css
> +/* .footer .container {
это мои эксперименты остались, убрал.

2021-01-09 10:22 UTC, Grek-88 commented on css/style.css
> +  /* border: 2px solid green; */
убрал

2021-01-09 14:59 UTC, magom001 commented on css/style.css
> +  border: 1px solid #eeeeee;
точно!

2021-01-09 15:00 UTC, magom001 commented on css/style.css
> +  border: 1px solid #eeeeee;
P.S.: #eee один из самых распространенных серых

2021-01-09 15:03 UTC, magom001 commented on css/style.css
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 1px rgba(0, 0, 0, 0.14),
👍🏻

2021-01-09 15:04 UTC, magom001 commented on css/style.css
> +  background: var(--color-backgroun);
`--color-backgroun` -> `--color-background`

2021-01-09 15:04 UTC, magom001 approved these changes

2021-01-09 15:07 UTC, Grek-88 commented on css/style.css
> +  border: 1px solid #eeeeee;
спасибо не знал, уберу в переменную тогда

2021-01-09 15:10 UTC, Grek-88 commented on css/style.css
> +  border: 1px solid #eeeeee;
уже убрал в переменную

2021-01-09 15:12 UTC, Grek-88 commented on css/style.css
> +  background: var(--color-backgroun);
добавил буковку везде

2021-01-09 15:13 UTC, merged